//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/SebastianDremo/Projects/Fluq/Parsing/Grammar/FluqParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FluqParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IFluqParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.fluq_program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFluq_program([NotNull] FluqParser.Fluq_programContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.fluq_program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFluq_program([NotNull] FluqParser.Fluq_programContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>var_assign</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_assign([NotNull] FluqParser.Var_assignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>var_assign</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_assign([NotNull] FluqParser.Var_assignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>func_declare</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_declare([NotNull] FluqParser.Func_declareContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>func_declare</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_declare([NotNull] FluqParser.Func_declareContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] FluqParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] FluqParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>newline</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewline([NotNull] FluqParser.NewlineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>newline</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewline([NotNull] FluqParser.NewlineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_declaration([NotNull] FluqParser.Func_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_declaration([NotNull] FluqParser.Func_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call([NotNull] FluqParser.Func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call([NotNull] FluqParser.Func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_body([NotNull] FluqParser.Func_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_body([NotNull] FluqParser.Func_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_declaration_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_declaration_params([NotNull] FluqParser.Func_declaration_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_declaration_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_declaration_params([NotNull] FluqParser.Func_declaration_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_call_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call_params([NotNull] FluqParser.Func_call_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_call_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call_params([NotNull] FluqParser.Func_call_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>print</c>
	/// labeled alternative in <see cref="FluqParser.built_in_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] FluqParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>print</c>
	/// labeled alternative in <see cref="FluqParser.built_in_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] FluqParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.print_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_func([NotNull] FluqParser.Print_funcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.print_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_func([NotNull] FluqParser.Print_funcContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr([NotNull] FluqParser.StrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr([NotNull] FluqParser.StrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>var</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] FluqParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>var</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] FluqParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum([NotNull] FluqParser.NumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum([NotNull] FluqParser.NumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>math</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMath([NotNull] FluqParser.MathContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>math</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMath([NotNull] FluqParser.MathContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bracket_expr</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracket_expr([NotNull] FluqParser.Bracket_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bracket_expr</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracket_expr([NotNull] FluqParser.Bracket_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>text</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] FluqParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>text</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] FluqParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt([NotNull] FluqParser.IntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt([NotNull] FluqParser.IntContext context);
}
