//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/SebastianDremo/Projects/Fluq/Parsing/Grammar/FluqParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFluqParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FluqParserBaseListener : IFluqParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.fluq_program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFluq_program([NotNull] FluqParser.Fluq_programContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.fluq_program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFluq_program([NotNull] FluqParser.Fluq_programContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>var_assign</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_assign([NotNull] FluqParser.Var_assignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>var_assign</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_assign([NotNull] FluqParser.Var_assignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>func_declare</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_declare([NotNull] FluqParser.Func_declareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>func_declare</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_declare([NotNull] FluqParser.Func_declareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] FluqParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] FluqParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>newline</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewline([NotNull] FluqParser.NewlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>newline</c>
	/// labeled alternative in <see cref="FluqParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewline([NotNull] FluqParser.NewlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_declaration([NotNull] FluqParser.Func_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_declaration([NotNull] FluqParser.Func_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call([NotNull] FluqParser.Func_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call([NotNull] FluqParser.Func_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_body([NotNull] FluqParser.Func_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_body([NotNull] FluqParser.Func_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_declaration_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_declaration_params([NotNull] FluqParser.Func_declaration_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_declaration_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_declaration_params([NotNull] FluqParser.Func_declaration_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.func_call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call_params([NotNull] FluqParser.Func_call_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.func_call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call_params([NotNull] FluqParser.Func_call_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>print</c>
	/// labeled alternative in <see cref="FluqParser.built_in_func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] FluqParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>print</c>
	/// labeled alternative in <see cref="FluqParser.built_in_func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] FluqParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FluqParser.print_func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_func([NotNull] FluqParser.Print_funcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FluqParser.print_func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_func([NotNull] FluqParser.Print_funcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>str</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr([NotNull] FluqParser.StrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>str</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr([NotNull] FluqParser.StrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>var</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] FluqParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>var</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] FluqParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum([NotNull] FluqParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum([NotNull] FluqParser.NumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>math</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMath([NotNull] FluqParser.MathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>math</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMath([NotNull] FluqParser.MathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bracket_expr</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBracket_expr([NotNull] FluqParser.Bracket_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bracket_expr</c>
	/// labeled alternative in <see cref="FluqParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBracket_expr([NotNull] FluqParser.Bracket_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>text</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] FluqParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>text</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] FluqParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] FluqParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="FluqParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] FluqParser.IntContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
